# lightning.pytorch==2.0.6
seed_everything: 12345
trainer:
  #######  for testing
  accelerator: cpu
  devices: 1
  #######
  benchmark: true # speeds up training time
data:
  batch_size: 24
ckpt_path: lightning_logs/version_149/checkpoints/checkpoint.ckpt