# lightning.pytorch==2.0.6
seed_everything: 12345
trainer:
  num_sanity_val_steps: 0
  # devices: 1
  # detect_anomaly: true
  # profiler:
  #   class_path: lightning.pytorch.profilers.AdvancedProfiler
  #   init_args:
  #     filename: profiler
  #     dirpath: .
  # strategy: ddp_find_unused_parameters_true
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 15
        mode: min
        monitor: validation_loss
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: validation_loss
        mode: min
        filename: checkpoint
  # fast_dev_run: true
  max_epochs: 30
  # limit_train_batches: 0.01
  # limit_val_batches: 0.01
  
  # max_steps: 2
  # deterministic: true # slows down training time
  benchmark: true # speeds up training time
# model:
#   lr: 0.0005
#   wd: 0.0001
data:
  batch_size: 16
# ckpt_path: lightning_logs/version_150/checkpoints/checkpoint.ckpt


# # lightning.pytorch==2.0.6
# seed_everything: 12345
# trainer:
#   callbacks:
#     - class_path: lightning.pytorch.callbacks.EarlyStopping
#       init_args:
#         patience: 15
#         mode: min
#         monitor: validation_loss
#     - class_path: lightning.pytorch.callbacks.ModelCheckpoint
#       init_args:
#         monitor: validation_loss
#         mode: min
#         filename: checkpoint
#   max_epochs: 50
#   benchmark: true
# data:
#   batch_size: 16